name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths: [ "backend/**" ]

jobs:
  flyio:
    name: Fly.io Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        working-directory: backend
        run: flyctl deploy -c fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
